[outputs]
url_prefix=/admin/system/dashboard/
webui_allowed_hosts=127.0.0.1,localhost
cors_origins=http://127.0.0.1
cors_methods=GET,HEAD
cors_credentials=False
max_processes_display=15

[ip]
# Do not query external services to discover the public IP.
disable=True

[cloud]
disable=True

[containers]
disable=True
