# Generated by Django 5.2.17 on 2026-09-23 21:28

import django.core.validators
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Smaller numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("work", "Work"), ("education", "Education")],
                        max_length=10,
                    ),
                ),
                ("position", models.CharField(max_length=250)),
                ("company", models.CharField(max_length=250)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("type", models.CharField(blank=True, max_length=80)),
                ("duration", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Smaller numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        validators=[portfolio.validators.image_url],
                    ),
                ),
                ("description", models.TextField()),
                ("techstack", models.CharField(blank=True, max_length=500)),
                (
                    "preview_link",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Smaller numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkdein", "LinkedIn"),
                            ("github", "GitHub"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=1000,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Smaller numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "group",
                    models.CharField(
                        choices=[("stack", "Tech stack"), ("tool", "Tools")],
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=1000, validators=[portfolio.validators.image_url]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "technologies",
                "ordering": ["order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("about", models.TextField()),
                (
                    "image",
                    models.CharField(
                        max_length=1000, validators=[portfolio.validators.image_url]
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        max_length=1000, validators=[portfolio.validators.image_url]
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Display text; obfuscated addresses are supported.",
                        max_length=254,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=80)),
                (
                    "coding_challenges_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("footer_text", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "site profile",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="single_site_profile"
                    )
                ],
            },
        ),
    ]
