# Generated by Django 5.2.17 on 2026-09-23 22:32

from django.db import migrations, models


SITE_COPY = {
    "home_greeting": "Hi,👋",
    "home_name_leadin": "My Name is",
    "about_heading": "About Me",
    "experience_heading": "Work Experience",
    "education_heading": "Education",
    "projects_heading": "Selected Projects",
    "contact_heading": "Feel Free to connect wtih me:",
    "technologies_heading": "Tech Stack",
    "technologies_intro": "Technologies I've been working with recently",
    "tools_heading": "Tools",
    "nav_home": "Home",
    "nav_about": "About",
    "nav_technologies": "Technologies",
    "nav_projects": "Projects",
    "nav_contact": "Contact",
    "coding_challenges_label": "Coding challenges",
    "project_keywords_label": "Keywords",
    "project_preview_label": "Live Preview",
    "project_code_label": "View Code",
    "footer_admin_label": "Admin",
}


def seed_site_copy(apps, schema_editor):
    SiteText = apps.get_model("portfolio", "SiteText")
    manager = SiteText.objects.using(schema_editor.connection.alias)
    for key, text in SITE_COPY.items():
        manager.get_or_create(key=key, defaults={"text": text})


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_initial_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("home_greeting", "Home — greeting"),
                            ("home_name_leadin", "Home — name introduction"),
                            ("about_heading", "About — page heading"),
                            ("experience_heading", "About — work heading"),
                            ("education_heading", "About — education heading"),
                            ("projects_heading", "Projects — page heading"),
                            ("contact_heading", "Contact — page heading"),
                            ("technologies_heading", "Technologies — page heading"),
                            ("technologies_intro", "Technologies — introduction"),
                            ("tools_heading", "Technologies — tools heading"),
                            ("nav_home", "Navigation — home"),
                            ("nav_about", "Navigation — about"),
                            ("nav_technologies", "Navigation — technologies"),
                            ("nav_projects", "Navigation — projects"),
                            ("nav_contact", "Navigation — contact"),
                            (
                                "coding_challenges_label",
                                "Navigation — coding challenges",
                            ),
                            ("project_keywords_label", "Project card — keywords"),
                            ("project_preview_label", "Project card — live preview"),
                            ("project_code_label", "Project card — view code"),
                            ("footer_admin_label", "Footer — admin link"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("text", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "site text",
                "verbose_name_plural": "site text and labels",
                "ordering": ["key"],
            },
        ),
        migrations.RunPython(seed_site_copy, migrations.RunPython.noop),
    ]
