# Generated by Django 5.2.17 on 2026-09-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_sitetext"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminToolAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin tool access",
                "permissions": [
                    (
                        "view_visitor_analytics",
                        "Can view visitor analytics (includes IP addresses)",
                    ),
                    ("view_system_health", "Can view system health"),
                    ("view_camera", "Can view live camera"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
