# Generated by Django 5.2.17 on 2026-09-26 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("path", models.CharField(max_length=64)),
                ("referrer", models.CharField(blank=True, max_length=253)),
                ("browser", models.CharField(max_length=24)),
                ("device", models.CharField(max_length=16)),
            ],
            options={
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["ip_address", "occurred_at"], name="analytics_ip_time"
                    )
                ],
            },
        ),
    ]
